neve:
  dataSources:
    testDB:
      driverName: "mysql"
      driverInfo: "test:123@tcp(127.0.0.1:3306)/test?timeout=10s&readTimeout=15s&charset=uft8"
      maxConn: 1000
      maxIdleConn: 500
      connMaxLifetime: 15

gobatis:
  mapper:
    dir: "assets/mappers"
  log:
    level: DEBUG
  pagehelper:
    enable: true
